version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules # Evita que o volume local sobrescreva os módulos do container
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000 # URL do back-end local
