version: '3.8'

services:
  frontend:
    build:
      context: .
      target: ${DOCKER_TARGET_FRONT} # Lê do .env (dev ou prod)
    image: meu-projeto-frontend:latest
    container_name: frontend-container
    restart: always
    ports:
      - "${FRONT_PORT}:5173" # Local mapeia 5173:80 (Vite), Prod mapeia 80:80 (Nginx)
    volumes:
      # Esse volume só será usado se você estiver em modo dev (mapeando seu código local)
      - .:/app:ro
      - /app/node_modules
