services:
  frontend:
    build:
      context: .
      target: ${DOCKER_TARGET_FRONT:-dev}
    image: meu-projeto-frontend:latest
    container_name: frontend-container
    restart: always
    ports:
      - "${FRONT_PORT:-5173}:${FRONT_CONTAINER_PORT:-5173}"
    volumes:
      # Se as variáveis estiverem vazias, o Docker ignora a montagem
      - ${LOCAL_CODE_PATH:-./}:${LOCAL_CONTAINER_PATH:-/app}:ro
      - ${LOCAL_NODE_MODULES:-/app/node_modules}
