name: Deploy Front-end Local

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, prod-front]
    
    environment: production

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Compilar Imagem de Produção e Iniciar Container
      env:
        DOCKER_TARGET_FRONT: prod
        FRONT_PORT: 80
        FRONT_CONTAINER_PORT: 80
        LOCAL_CODE_PATH: /usr/share/nginx/html
        LOCAL_CONTAINER_PATH: /usr/share/nginx/html
        LOCAL_NODE_MODULES: /usr/share/nginx/html
        VITE_API_URL: ${{ vars.VITE_API_URL }}
      run: |
        # Injeta a variável no build para que o Vite capture ela durante a compilação do React
        docker compose down || true
        docker rm -f frontend-container || true
        
        # Passamos a variável de ambiente para o comando build do compose ler
        VITE_API_URL=$VITE_API_URL docker compose build --no-cache frontend
        docker compose up -d frontend