name: Deploy Front-end Local

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, prod-front]
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Compilar Imagem de Produção e Iniciar Container
      run: |
        # Injeta as variáveis para o Compose saber que deve compilar o estágio 'prod'
        export DOCKER_TARGET_FRONT=prod
        export FRONT_PORT=80
        
        # Reconstrói a imagem localmente usando o código recém-baixado pelo checkout
        docker compose build --no-cache frontend
        
        # Sobe o container atualizado
        docker compose up -d --force-recreate frontend
